### ISSUE TITLE
Getting NoMethodError on Ruby 2.3.1

### ISSUE THREAD

**Issue by colindean** [mroth/lolcommits#314]
```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc5f5c12ce4 lolcommits-0.8.0> (NoMethodError)
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/lolcommits-0.8.0/bin/lolcommits:5:in `<top (required)>'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/lolcommits:23:in `load'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/lolcommits:23:in `<main>'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Just upgraded yesterday. I'm not sure what's wrong and I don't have time at the moment to investigate.

**Comment by matthutchinson** [comment]
interesting, i'll take a look this weekend - for now downgrading to the previous version should fix it

**Comment by matthutchinson** [comment]
can I ask, what does `gem --version` give you?

**Comment by colindean** [comment]
```
$ gem --version
2.5.1
```

**Comment by colindean** [comment]
I was getting it on lolcommits 0.6.5, too. Upgraded to 0.8.0 trying to get around it.

**Comment by matthutchinson** [comment]
not much has changed between 0.6.5 and 0.80 ... but thats useful info - I'll try to dig into it

**Comment by matthutchinson** [comment]
So I just tried this (on OSX/rbenv) with a fresh copy of Ruby 2.3.1, RubyGems 2.5.1 and lolcommits (0.8.0) and it all installed OK..

Looking at your backtrace, it seems like you have RVM installed - so unless there is something specific with that setup .. but I doubt it.  Given I also see `/usr/local/Cellar/` in the backtrace, I assume you are running on OSX?  

If possible, i'd suggest trying to uninstall ruby 2.3.1 from rvm and trying again. Finally what does this give you;

    which ruby
    which gem

**Comment by colindean** [comment]
reinstalled 2.3.1 and lolcommits and now it works. I guess I got a bad build or migration of 2.2.1 ➡️  2.3.1?

**Comment by colindean** [comment]
Spoke too soon. Just running it worked, but when I did a commit, bam:

```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Users/cdean/.rvm/gems/ruby-2.3.1/gems/http_parser.rb-0.6.0/lib/ruby_http_parser.bundle (fatal)
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:5:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/twitter-5.16.0/lib/twitter.rb:26:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/lolcommits-0.8.0/lib/lolcommits/plugins/lol_twitter.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/lolcommits-0.8.0/lib/lolcommits.rb:35:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/gems/lolcommits-0.8.0/bin/lolcommits:5:in `<top (required)>'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/lolcommits:23:in `load'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/lolcommits:23:in `<main>'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/cdean/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by matthutchinson** [comment]
there could be some PATH problems with your machine and rvm... 
`incompatible library version` usually happens when the Ruby in your ENV is trying to run a binary with code compiled for a different version of Ruby.

So the gem is now installed?  What happens when you run these commands in your git repo folder;

```
lolcommits -v
lolcommits --enable
cat .git/hooks/post-commit
lolcommits -c --debug
lolcommits -b
```

**Comment by matthutchinson** [comment]
Also, maybe try reinstalling the [http_parser](https://rubygems.org/gems/http_parser.rb) gem with;

```
# first make sure you are on Ruby 2.3.1 with ram
rvm use 2.3.1
gem uninstall http_parser
# remove all versions if you have multiple
gem clean
gem install http_parser
```

**Comment by colindean** [comment]
```
[11:45:29 cdean@lusankya.uspa.ibm.com ~/Source/myproject/stuff (ruby-2.3.1)]
± (colindean/better-timeouts *%) $ lolcommits -v
0.8.0
[14:09:39 cdean@lusankya.uspa.ibm.com ~/Source/myproject/stuff (ruby-2.3.1)]
± (colindean/better-timeouts *%) $ lolcommits --enable
installed lolcommit hook to:
  -> /Users/cdean/Source/myproject/stuff/.git/hooks/post-commit
(to remove later, you can use: lolcommits --disable)
[14:09:40 cdean@lusankya.uspa.ibm.com ~/Source/myproject/stuff (ruby-2.3.1)]
± (colindean/better-timeouts *%) $ cat .git/hooks/post-commit
#!/bin/sh
### lolcommits hook (begin) ###
if [ ! -d "$GIT_DIR/rebase-merge" ]; then
export LANG="en_US.UTF-8"
export PATH="/Users/cdean/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:$PATH"
lolcommits --capture
fi
###  lolcommits hook (end)  ###
[14:09:40 cdean@lusankya.uspa.ibm.com ~/Source/myproject/stuff (ruby-2.3.1)]
± (colindean/better-timeouts *%) $ lolcommits -c --debug
Outputting at DEBUG verbosity
Walking up dir tree
GitInfo: parsed the following values from commit:
GitInfo: 	Fixes file naming
GitInfo: 	7343554148b
GitInfo: 	/Users/cdean/Source/myproject/stuff/.git
GitInfo: 	watson-stuff/stuff
GitInfo: 	colindean/better-timeouts
GitInfo: 	Colin Dean
GitInfo: 	<email redacted>
Runner: precapture about to execute Lolcommits::Tranzlate
Plugin: Lolcommits::Tranzlate: Initializing
Plugin: Lolcommits::Tranzlate: Disabled, doing nothing for precapture execution
*** Preserving this moment in history.
Capturer: initializing new instance #<Lolcommits::CaptureMac:0x007fb7b0041cc0>
Capturer: making system call for /Users/cdean/.rvm/gems/ruby-2.3.1/gems/lolcommits-0.8.0/lib/lolcommits/../../vendor/ext/imagesnap/imagesnap -q "/Users/cdean/.lolcommits/stuff/tmp_snapshot.jpg" -w 0
Runner: resizing snapshot
Runner: writing resized image to /Users/cdean/.lolcommits/stuff/tmp_snapshot.jpg
Runner: copying resized image to /Users/cdean/.lolcommits/stuff/7343554148b.jpg
Plugin: Lolcommits::Loltext: Initializing
Plugin: Lolcommits::Loltext: I am enabled, about to run postcapture
Plugin: Lolcommits::Loltext: Annotating image via MiniMagick
Plugin: Lolcommits::Loltext: annotating message to image with Fixes file naming
Plugin: Lolcommits::Loltext: annotating sha to image with 7343554148b
Plugin: Lolcommits::Loltext: Writing changed file to /Users/cdean/.lolcommits/stuff/7343554148b.jpg
Runner: postcapture about to execute Lolcommits::DotCom
Plugin: Lolcommits::DotCom: Initializing
Plugin: Lolcommits::DotCom: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::LolYammer
Plugin: Lolcommits::LolYammer: Initializing
Plugin: Lolcommits::LolYammer: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::LolProtonet
Plugin: Lolcommits::LolProtonet: Initializing
Plugin: Lolcommits::LolProtonet: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::LolTwitter
Plugin: Lolcommits::LolTwitter: Initializing
Plugin: Lolcommits::LolTwitter: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::LolSlack
Plugin: Lolcommits::LolSlack: Initializing
Plugin: Lolcommits::LolSlack: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::LolTumblr
Plugin: Lolcommits::LolTumblr: Initializing
Plugin: Lolcommits::LolTumblr: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::Uploldz
Plugin: Lolcommits::Uploldz: Initializing
Plugin: Lolcommits::Uploldz: Disabled, doing nothing for postcapture execution
Runner: postcapture about to execute Lolcommits::Lolsrv
Plugin: Lolcommits::Lolsrv: Initializing
Plugin: Lolcommits::Lolsrv: Disabled, doing nothing for postcapture execution
Runner: running cleanup
[14:09:43 cdean@lusankya.uspa.ibm.com ~/Source/myproject/stuff (ruby-2.3.1)]
± (colindean/better-timeouts *%) $ lolcommits -b
[14:09:49 cdean@lusankya.uspa.ibm.com ~/Source/myproject/stuff (ruby-2.3.1)]
± (colindean/better-timeouts *%) $
```

**Comment by matthutchinson** [comment]
Wow, ok it looks like everything is working fine there, with `lolcommits -b` you should have seen your capture in the lolcommits folder.

So if its not working from the post-commit hook - there are a couple of ways to debug;
First, edit the file at `.git/hooks/post-commit` and change it to;


#!/bin/sh
### lolcommits hook (begin) ###
if [ ! -d "$GIT_DIR/rebase-merge" ]; then
export LANG="en_US.UTF-8"
export PATH="/Users/cdean/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:$PATH"

  echo $PATH
  echo `which lolcommits`
  echo `which ruby`

lolcommits --capture

fi
###  lolcommits hook (end)  ###



Then just call the hook directly from the command line with;

    .git/hooks/post-commit

Can I ask what command you are running when you commit with git? or are you using a Git GUI?

**Comment by colindean** [comment]
It appears to be working now after uninstalling ruby 2.3.1 and reinstalling it. I think the rvm upgrade from 2.2.1 to 2.3.1 broke something.

**Comment by matthutchinson** [comment]
Glad you got it sorted out 👍 & thanks for closing the issue.
