### ISSUE TITLE
Handle git external worktrees correctly

### ISSUE THREAD

**Issue by Khoyo** [mroth/lolcommits#324]
Ass of now, if you have a repository named foo, and you create an external worktree, lolcommits gets confused and think you aren't in a git repository when committing from the external worktree

[foo] $ git worktree add ../foo-hotfix
[foo] $ cd ../foo-hotfix
...
Do some work...
...
[foo-hotfix] $ git commit
Repository root not found
/home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/lib/lolcommits/runner.rb:23:in `initialize': Unknown VCS (RuntimeError)
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/bin/lolcommits:104:in `new'
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/bin/lolcommits:104:in `block in do_capture'
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/lib/lolcommits/cli/process_runner.rb:25:in `block in fork_me?'
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/lib/lolcommits/cli/process_runner.rb:24:in `fork'
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/lib/lolcommits/cli/process_runner.rb:24:in `fork_me?'
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/bin/lolcommits:87:in `do_capture'
	from /home/khoyo/.gem/ruby/2.3.0/gems/lolcommits-0.8.1/bin/lolcommits:321:in `<top (required)>'
	from /home/khoyo/.gem/ruby/2.3.0/bin/lolcommits:23:in `load'
	from /home/khoyo/.gem/ruby/2.3.0/bin/lolcommits:23:in `<main>'

**Comment by drdanz** [comment]
I can confirm the problem is still present in v0.12.1, but the message is now "You don't appear to be in a directory of a supported vcs project."

**Comment by gnutix** [comment]
That's too bad. I would have enjoyed reinstalling lolcommits, but I mostly work in worktrees now. :(
