### ISSUE TITLE
lolcommits cannot be installed on High Sierra

### ISSUE THREAD

**Issue by guperrot** [mroth/lolcommits#364]
```
$ sudo gem install lolcommits --backtrace
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/installer.rb:233:in `check_executable_overwrite'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/installer.rb:474:in `block in generate_bin'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/installer.rb:461:in `each'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/installer.rb:461:in `generate_bin'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/installer.rb:301:in `install'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/resolver/specification.rb:97:in `install'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/request_set.rb:166:in `block in install'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/request_set.rb:156:in `each'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/request_set.rb:156:in `install'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:250:in `install_gem'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
	/usr/bin/gem:21:in `<main>'

$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
```

Also a previous installation of lolcommits before updating to High Sierra is also broken:

```
lolcommits --enable --delay 1 --animate 3 --fork
-bash: /usr/local/bin/lolcommits: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
```

**Comment by guperrot** [comment]
Not a lolcommits issue but os upgrading issue.

I had to follow this: https://stackoverflow.com/a/40150951/598520

Then I reinstalled the gems, then I had to manually fix the link to /usr/local/bin to point to the new gems (for some reason gem install won't update that).

**Comment by matthutchinson** [comment]
Closing this one, it seems to be an OS / Ruby issue.
