### ISSUE TITLE
Library not loaded: /usr/local/lib/libMagickCore.4.dylib (LoadError)

### ISSUE THREAD

**Issue by jpsilvashy** [mroth/lolcommits#9]
I installed imagemagick with brew but I'm having a strange issue still:

```
/Users/jpsilvashy/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-2.13.1/lib/RMagick2.bundle: dlopen(/Users/jpsilvashy/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-2.13.1/lib/RMagick2.bundle, 9): Library not loaded: /usr/local/lib/libMagickCore.4.dylib (LoadError)
  Referenced from: /Users/jpsilvashy/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-2.13.1/lib/RMagick2.bundle
  Reason: image not found - /Users/jpsilvashy/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-2.13.1/lib/RMagick2.bundle
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Users/jpsilvashy/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-2.13.1/lib/RMagick.rb:11
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/jpsilvashy/.git_hooks/post-commit//lolcommit:4
```

Not sure what to do, I tried unlinking and reinstalling imagemagick with no luck.

**Comment by NZQiu** [comment]
+1 gem pristine rmagick

**Comment by shubhamkukreja830** [comment]
+1 gem pristine rmagick

**Comment by abuisman** [comment]
+1 pristine

**Comment by mushsong** [comment]
+1 gem pristine rmagick
